  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=roomies
        - POSTGRES_USER=oseishon
        - POSTGRES_PASSWORD=zxcv1234
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:9000
      volumes:
        - .:/code
      ports:
        - "9000:9000"
      depends_on:
        - db