# Generated by Django 3.1 on 2020-09-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0002_auto_20200922_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_estatus',
            field=models.ForeignKey(db_column='id_estatus', on_delete=django.db.models.deletion.CASCADE, to='usr.estatus'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(db_column='id_roles', on_delete=django.db.models.deletion.CASCADE, to='usr.roles'),
        ),
    ]
