# Generated by Django 3.1 on 2020-09-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_auto_20200922_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_estatus',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_rol',
        ),
    ]
