# Generated by Django 3.1 on 2020-09-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0006_auto_20200922_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estatus',
        ),
    ]
